### PR TITLE
Adding support to handle multiple artifacts

### PR DESCRIPTION
**Pull request by jjbustamante**
## Summary

The idea behind this changes is extend the behavior of the `ArtifactResolver` to handle more than 1 artifact after a build is executed. Currently, we are expecting just 1 file (zip equivalent format), this file is zipped, copy to the /layer and then restore in /workspace. 

The `Pattern()` regular expression is evaluated and the result is analize following these rules

- It matches a single file (current behavior)
- It matches multiple files (multi-file behavior)
- It matches a folder (take everything in the folder, then multi-file behavior)
- It matches multiple folders (take everything in every folder, then multi-file behavior)

## Use Cases
The initial particular use case for this feature is to help the native-image creation of an application from source code that is not exploded, for example, in case of Quarkus application a folder with all the dependencies require build the native-image can be created using the variable: `-Dquarkus.package.type=native-sources` for example in Maven, the output of this build is a folder in my build directory with a structure similar to this:

```
target/native-sources
├── target/native-sources
├── lib
└── native-image.args
```

In this particular case, this PR can handle the result of this build an copy all the files inside the `target/native-sources` folder

This PR Fixes paketo-buildpacks/maven/issues/76

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
@jjbustamante I did a review of this and dug around through the code. The gist of what you have looks good to me.

I pushed [this branch](https://github.com/paketo-buildpacks/libbs/tree/jjbustamante-feature/support-multiple-artifacts-of-different-types) with some ideas to reduce some of the code, some additional tests I wanted to see, and also a change to the behavior of how we store folders under the layer.

Can you take a look and let me know what you think? In particular, about the last bit. That will change the structure of what is restored into the `/workspace`, so I want to make sure that will be OK for your usecase.

Thanks!

**Comment by jjbustamante** [comment]
> @jjbustamante I did a review of this and dug around through the code. The gist of what you have looks good to me.
> 
> I pushed [this branch](https://github.com/paketo-buildpacks/libbs/tree/jjbustamante-feature/support-multiple-artifacts-of-different-types) with some ideas to reduce some of the code, some additional tests I wanted to see, and also a change to the behavior of how we store folders under the layer.
> 
> Can you take a look and let me know what you think? In particular, about the last bit. That will change the structure of what is restored into the `/workspace`, so I want to make sure that will be OK for your usecase.
> 
> If that all looks good, I can merge that branch into main.
> 
> Thanks!

I @dmikusa-pivotal thanks for the review and the feedback!!

Let me take a look at it, but more importantly, I will run the use case I was testing which is building a Quarkus sample app from the started guide using Pack + Buildpack! I will let you know if everything is still working with this branch

**Comment by jjbustamante** [comment]
Hi @dmikusa-pivotal.

I tried to test this branch on my local with the Quarkus project I was using before, but when I tried to build the Maven Buildpack pointing to the branch I am getting this:

Screen Shot 2022-01-20 at 4 50 14 PM

The only thing I did was to add this line into the go.mod

```
replace github.com/buildpacks/libcnb => ../libbs
```

**Comment by dmikusa-pivotal** [comment]
I have not had good luck with relative paths in replace statements for go.mod files. Perhaps try a full path? I'm not sure if relative is supposed to work or not. I just always use full paths.

**Comment by jjbustamante** [comment]
Sorry, my mistake @dmikusa-pivotal.  I was replacing libcnb instead of libbs :$

**Comment by jjbustamante** [comment]
@dmikusa-pivotal 

I tested the [branch](https://github.com/paketo-buildpacks/libbs/tree/jjbustamante-feature/support-multiple-artifacts-of-different-types)  and it worked, I managed to build the native image changing the path where the artifacts are copied. 

Screen Shot 2022-01-20 at 6 29 16 PM
Screen Shot 2022-01-20 at 6 29 25 PM

I need to modify the native-image [PR](https://github.com/paketo-buildpacks/native-image/pull/124) to handle this (for testing I hardcoded to run the validation), I will also check some comments you left there. From my side, I am happy with this new branch!

**Comment by dmikusa-pivotal** [comment]
OK, I submitted & merged https://github.com/paketo-buildpacks/libbs/pull/100. Closing this.

**Pull request closed without merging**
